# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 391384d90451492d3ea1c9a8c62dacc1d59c4b071cf0390823644942f625de344de818e16e49743de5119920fabc3765079ade8a7feba52bf27865badfe4e295

test:
  secret_key_base: 39299f25ba1229312320808e60ccf5b5ea6c7dcb1d3af251399b77442ea83f16878bca72fa44b828128d6aa78ce42b8878eeb1be5528b22cdd749fd796ed9df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
